spring.application.name=kanban
spring.data.mongodb.uri=mongodb+srv://barusubarubarusu333_db_user:XcXaWpMW80Ni18Zo@cluster0.vxn6a3c.mongodb.net/devsprint?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=devsprint
server.port=8080
spring.data.mongodb.auto-index-creation=true
