spring.application.name=gestionlabs
spring.data.mongodb.uri=mongodb+srv://nik:2030@cluster0.h5wdohm.mongodb.net/gestionlabs?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=gestionlabs
server.port=9090
spring.data.mongodb.auto-index-creation=true

# Springdoc / Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Logging temporal para ver rutas mapeadas
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
