spring.application.name=gestionlabs
spring.data.mongodb.uri=mongodb+srv://barusubarubarusu333_db_user:XcXaWpMW80Ni18Zo@cluster0.vxn6a3c.mongodb.net/gestionlabs?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=gestionlabs
server.port=8080
spring.data.mongodb.auto-index-creation=true
